/**
 * @param {import('knex').Knex} knex
 */
export async function seed(knex) {
  await knex('order_items').del();
  await knex('orders').del();
  await knex('products').del();

  await knex('products').insert([
    {
      id: 1,
      name: 'Le Male',
      category: 'men',
      price: 100,
      discount: 15,
      stock: 10,
      image: '/images/lemaleparfume.webp',
      description: 'Amber aromatik. Yalpizning kuchi va tetikligi. Soqol olish sovunining tanish, taskin beruvchi hidini uyg\'otadigan lavanda vanilning nozikligi bilan o\'zgaradi.',
      created_at: new Date('2025-01-01'),
    },
    {
      id: 2,
      name: 'Le Male in Blue',
      category: 'men',
      price: 129.99,
      discount: 10,
      stock: 5,
      image: '/images/Le_Male_in_Blue.png',
      description: 'Achchiq aromatik. Le Male In Blue to\'g\'ri oldinda siljiydi. Uning achchiq xushbo\'y izi yo\'nalishni belgilaydi va to\'lqinni chaqiradi.',
      created_at: new Date('2025-01-05'),
    },
    {
      id: 3,
      name: 'Le Male Elixir Absolu',
      category: 'men',
      price: 110,
      discount: 20,
      stock: 0,
      image: '/images/Le_Male_Elixir_Absolu.png',
      description: 'Achchiq aromatik kehribar. Ushbu Male terisida oltin rangli xushbo\'y hid taraladi. Mutlaq boylik.',
      created_at: new Date('2025-01-10'),
    },
    {
      id: 4,
      name: 'Le Male Elixir',
      category: 'men',
      price: 159.99,
      discount: 0,
      stock: 8,
      image: '/images/Le_Male_Elixir_Absolu.png',
      description: 'Yog\'ochli aromatik kehribar. Bu kuchli xushbo\'y hid uning tanasining yumshoq terisida yonib turgan hissiyotlarni qoldiradi.',
      created_at: new Date('2025-01-15'),
    },
    {
      id: 5,
      name: 'Le Male Le Parfum',
      category: 'men',
      price: 109.99,
      discount: 25,
      stock: 12,
      image: '/images/Le_Male_Le_Parfum.png',
      description: 'VUDI Oriental. Yuqori notalaridagi kardamonning kuchi va markazidagi lavanta va irisning tazeligidan foydalanadi.',
      created_at: new Date('2025-01-20'),
    },
    {
      id: 6,
      name: 'LE BEAU NARCISSE',
      category: 'men',
      price: 119.99,
      discount: 12,
      stock: 3,
      image: '/images/LE_BEAU_NARCISSE.png',
      description: 'Amber Masky Woody. Le Beau Narcisse o\'zini oltin bilan qoplangan jannatdagi yorug\'lik portlashi kabi tasdiqlaydi.',
      created_at: new Date('2025-01-25'),
    },
    {
      id: 7,
      name: 'Le Beau Flower Edition',
      category: 'men',
      price: 99.99,
      discount: 18,
      stock: 15,
      image: '/images/Le_Beau_Flower_Edition.png',
      description: 'YOG\'OCHLI, gulli, mevali. Bu hid bizni o\'zining yangi sitrus va yog\'ochli notalari bilan ta\'minlaydi.',
      created_at: new Date('2025-01-02'),
    },
    {
      id: 8,
      name: 'Le Beau Paradise Garden',
      category: 'men',
      price: 109.99,
      discount: 22,
      stock: 0,
      image: '/images/Le_Beau_Paradise_Garden.png',
      description: 'YASHIL SUVLI VOODI. Ushbu atir sizni quyoshli jannatga xushbo\'yd sayohatiga olib borsin.',
      created_at: new Date('2025-01-06'),
    },
    {
      id: 9,
      name: 'Le Beau Le Parfum',
      category: 'men',
      price: 89.99,
      discount: 30,
      stock: 7,
      image: '/images/Le_Beau_Le_Parfum.png',
      description: 'Woody Amber. Gunohkorona sehr! Yaratuvchisining Adan bog\'idan uzib olingan bu kuchli Parfumning yog\'ochli jozibasi.',
      created_at: new Date('2025-01-12'),
    },
    {
      id: 10,
      name: 'Le Beau',
      category: 'men',
      price: 89.99,
      discount: 30,
      stock: 20,
      image: '/images/Le_Beau.png',
      description: 'Xushbo\'y Woody. Xushbo\'y yog\'ochli tualet suvining erkaklik tazeligi.',
      created_at: new Date('2025-01-12'),
    },
    {
      id: 11,
      name: 'Gaultier Divine Couture',
      category: 'women',
      price: 120,
      discount: 15,
      stock: 6,
      image: '/images/Gaultier_Divine_Couture.png',
      description: 'Mevali kehribar. Yaltiroq malina markaziy o\'rinni egallaydi — yorqin, o\'ynoqi va oddiy bo\'lmagan har qanday narsa.',
      created_at: new Date('2025-01-18'),
    },
    {
      id: 12,
      name: 'Gaultier Divine Elixir',
      category: 'women',
      price: 130,
      discount: 0,
      stock: 0,
      image: '/images/Gaultier_Divine_Elixir.png',
      description: 'Gulli dengiz kehribari. Gaultier Divine iksirga aylanganda, uning xushbo\'y hidi murosasiz ayollikni taratadi.',
      created_at: new Date('2025-01-22'),
    },
    {
      id: 13,
      name: 'GAULTIER DIVINE LE PARFUM',
      category: 'women',
      price: 100,
      discount: 20,
      stock: 9,
      image: '/images/GAULTIER_DIVINE_LE_PARFUM.png',
      description: 'Gulli, kehribar, dengiz rangi. Quyoshning yorqin notalari, dadil burilish va qo\'shimcha hissiyotlilik.',
      created_at: new Date('2025-01-28'),
    },
    {
      id: 14,
      name: 'Scandal Elixir',
      category: 'women',
      price: 99.99,
      discount: 20,
      stock: 4,
      image: '/images/Scandal_Elixir.png',
      description: 'Mevali kehribar chypre. Scandal Elixir bilan giyohvandlik hissiyotning yangi cho\'qqisiga chiqadi.',
      created_at: new Date('2025-01-28'),
    },
    {
      id: 15,
      name: 'Scandal Intense',
      category: 'women',
      price: 99.99,
      discount: 20,
      stock: 11,
      image: '/images/Scandal_Intense.png',
      description: 'Amber achchiq gulli. Oxirgi manzil sifatida qaramlik bilan birga jo\'hqin ayollik.',
      created_at: new Date('2025-01-29'),
    },
  ]);
}
